const deepFreeze = (value) => {
  if (value === null || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) deepFreeze(child);
  return Object.freeze(value);
};

const freezeEntries = (entries) => deepFreeze(entries.map((entry) => ({ ...entry })));

export const STAGE9_ARTIFACTS = freezeEntries(
  [
    ['ART-OPS-01', 'Reporte ejecutado de etapa 9', 'Markdown'],
    ['ART-OPS-02', 'Carta de operación y cierre', 'Markdown/tabla'],
    ['ART-OPS-03', 'Inventario final de recursos y dependencias', 'CSV/Markdown'],
    ['ART-OPS-04', 'Baseline operativa e identidad', 'JSON/Markdown'],
    ['ART-OPS-05', 'Dashboard y reporte de observación', 'Enlace/export'],
    ['ART-OPS-06', 'Matriz de alarmas y checks sintéticos', 'Markdown'],
    ['ART-OPS-07', 'Reporte de transacciones pendientes e invariantes', 'Markdown/CSV'],
    ['ART-OPS-08', 'Registro de incidentes y runbooks ejecutados', 'Markdown'],
    ['ART-OPS-09', 'Reporte de costes, presupuesto y tags', 'Markdown/CSV'],
    ['ART-OPS-10', 'Revisión de accesos, secretos y credenciales temporales', 'Markdown'],
    ['ART-OPS-11', 'Matriz de retención, eliminación y privacidad', 'Markdown'],
    ['ART-OPS-12', 'Plan y rehearsal de cleanup', 'Markdown/logs'],
    ['ART-OPS-13', 'Evidencia de decommission o retención autorizada', 'Markdown/logs'],
    ['ART-OPS-14', 'Índice de archivo de evidencia con checksums', 'Markdown/SHA-256'],
    ['ART-OPS-15', 'Plan de preservación/archivo del repositorio', 'Markdown'],
    ['ART-OPS-16', 'Retrospectiva y lecciones aprendidas', 'Markdown'],
    ['ART-OPS-17', 'Registro de riesgos residuales y aceptación', 'Markdown'],
    ['ART-OPS-18', 'Certificado final de cierre', 'Markdown/PDF opcional'],
  ].map(([id, name, format]) => ({ id, name, format, required: true })),
);

export const STAGE9_EVIDENCE = freezeEntries(
  [
    ['EVD-OPS-01', 'GATE-E8-03 y dictamen ACCEPTED'],
    ['EVD-OPS-02', 'Identidad de release y SHAs'],
    ['EVD-OPS-03', 'URLs operativas al inicio'],
    ['EVD-OPS-04', 'Inventario de recursos'],
    ['EVD-OPS-05', 'Tags y owners'],
    ['EVD-OPS-06', 'Dashboard inicial'],
    ['EVD-OPS-07', 'Dashboard final'],
    ['EVD-OPS-08', 'Matriz de alarmas'],
    ['EVD-OPS-09', 'Checks sintéticos'],
    ['EVD-OPS-10', 'Salud API/frontend'],
    ['EVD-OPS-11', 'Error rate y latencia'],
    ['EVD-OPS-12', 'Estado de reconciliador'],
    ['EVD-OPS-13', 'Transacciones PENDING al inicio'],
    ['EVD-OPS-14', 'Transacciones PENDING al cierre'],
    ['EVD-OPS-15', 'Invariantes de inventario'],
    ['EVD-OPS-16', 'Invariantes de entrega'],
    ['EVD-OPS-17', 'Revisión de logs sensibles'],
    ['EVD-OPS-18', 'Retención de logs'],
    ['EVD-OPS-19', 'Registro de incidentes'],
    ['EVD-OPS-20', 'Runbooks ejecutados'],
    ['EVD-OPS-21', 'Coste inicial'],
    ['EVD-OPS-22', 'Presupuesto/alertas'],
    ['EVD-OPS-23', 'Coste final o estimado residual'],
    ['EVD-OPS-24', 'Revisión de accesos'],
    ['EVD-OPS-25', 'Revocación de accesos temporales'],
    ['EVD-OPS-26', 'Inventario de secretos sin valores'],
    ['EVD-OPS-27', 'Política de retención aprobada'],
    ['EVD-OPS-28', 'Eliminación/anonymización de datos'],
    ['EVD-OPS-29', 'Rehearsal de cleanup'],
    ['EVD-OPS-30', 'Autorización de decommission/retención'],
    ['EVD-OPS-31', 'Ejecución de cleanup'],
    ['EVD-OPS-32', 'Verificación de recursos huérfanos'],
    ['EVD-OPS-33', 'Estado final de DNS/TLS/URLs'],
    ['EVD-OPS-34', 'Estado final de repositorio y README'],
    ['EVD-OPS-35', 'Índice de archivo y hashes'],
    ['EVD-OPS-36', 'Retrospectiva'],
    ['EVD-OPS-37', 'Riesgos residuales aceptados'],
    ['EVD-OPS-38', 'GATE-E9-01'],
    ['EVD-OPS-39', 'GATE-E9-02'],
    ['EVD-OPS-40', 'GATE-E9-03'],
    ['EVD-OPS-41', 'Certificado final'],
    ['EVD-OPS-42', 'Comunicación de cierre'],
    ['EVD-OPS-43', 'Fecha de expiración o destrucción'],
    ['EVD-OPS-44', 'Lista final de elementos retenidos y coste'],
  ].map(([id, name]) => ({ id, name, required: true })),
);

const audit = (id, name, expected, allowNotApplicable = false) => ({
  id,
  name,
  expected,
  allowNotApplicable,
  critical: !allowNotApplicable,
});

export const STAGE9_AUDIT_CONTROLS = freezeEntries([
  audit('OPSAUD-01', 'GATE-E8-03 verificable', 'PASS'),
  audit('OPSAUD-02', 'Release/SHAs/tag coinciden', 'PASS'),
  audit('OPSAUD-03', 'Carta completa', 'PASS'),
  audit('OPSAUD-04', 'Modo aprobado', 'PASS'),
  audit('OPSAUD-05', 'Roles definidos', 'PASS'),
  audit('OPSAUD-06', 'Autorizaciones registradas', 'PASS'),
  audit('OPSAUD-07', 'Inventario completo', 'PASS'),
  audit('OPSAUD-08', 'Recursos manuales identificados', 'PASS'),
  audit('OPSAUD-09', 'Tags sin PII', 'PASS'),
  audit('OPSAUD-10', 'Owners/expiry completos', 'PASS'),
  audit('OPSAUD-11', 'Dashboard inicial/final', 'PASS'),
  audit('OPSAUD-12', 'Alarmas con runbook', 'PASS'),
  audit('OPSAUD-13', 'Checks sintéticos ejecutados', 'PASS'),
  audit('OPSAUD-14', 'Salud frontend', 'PASS'),
  audit('OPSAUD-15', 'Salud API', 'PASS'),
  audit('OPSAUD-16', 'Error rate evaluado', 'PASS'),
  audit('OPSAUD-17', 'Latencia evaluada honestamente', 'PASS'),
  audit('OPSAUD-18', 'Reconciliador observado', 'PASS'),
  audit('OPSAUD-19', 'PENDING inicial/final', 'PASS'),
  audit('OPSAUD-20', 'Stock no negativo', 'PASS'),
  audit('OPSAUD-21', 'Sin doble decremento', 'PASS'),
  audit('OPSAUD-22', 'Sin entrega duplicada', 'PASS'),
  audit('OPSAUD-23', 'Clientes/entregas minimizados', 'PASS'),
  audit('OPSAUD-24', 'Logs estructurados', 'PASS'),
  audit('OPSAUD-25', 'Retención finita de logs', 'PASS'),
  audit('OPSAUD-26', 'Sin datos sensibles en logs', 'PASS'),
  audit('OPSAUD-27', 'Registro de incidentes', 'PASS'),
  audit('OPSAUD-28', 'P0/P1 cerrados', 'PASS'),
  audit('OPSAUD-29', 'Runbooks reproducibles', 'PASS'),
  audit('OPSAUD-30', 'Sandbox exclusivo', 'PASS'),
  audit('OPSAUD-31', 'Cuenta compartida no modificada', 'PASS'),
  audit('OPSAUD-32', 'Accesos inventariados', 'PASS'),
  audit('OPSAUD-33', 'Temporales revocados', 'PASS'),
  audit('OPSAUD-34', 'Secret scan final', 'PASS'),
  audit('OPSAUD-35', 'Secretos propios tratados', 'PASS'),
  audit('OPSAUD-36', 'Coste inicial/final', 'PASS'),
  audit('OPSAUD-37', 'Budget/alertas', 'PASS'),
  audit('OPSAUD-38', 'Recursos de coste huérfanos', '0'),
  audit('OPSAUD-39', 'Hold con expiry', 'PASS/N-A', true),
  audit('OPSAUD-40', 'Change freeze respetado', 'PASS'),
  audit('OPSAUD-41', 'Cambios de emergencia revalidados', 'PASS/N-A', true),
  audit('OPSAUD-42', 'Backup/export decidido', 'PASS'),
  audit('OPSAUD-43', 'Retención aprobada', 'PASS'),
  audit('OPSAUD-44', 'Datos eliminados/anonymizados', 'PASS/N-A', true),
  audit('OPSAUD-45', 'Evidencia con checksums', 'PASS'),
  audit('OPSAUD-46', 'Repo preservado/archivado correctamente', 'PASS'),
  audit('OPSAUD-47', 'README final', 'PASS'),
  audit('OPSAUD-48', 'Rehearsal de cleanup', 'PASS'),
  audit('OPSAUD-49', 'Destrucción autorizada', 'PASS/N-A', true),
  audit('OPSAUD-50', 'IaC cleanup ejecutado', 'PASS/N-A', true),
  audit('OPSAUD-51', 'Recursos retenidos inventariados', 'PASS/N-A', true),
  audit('OPSAUD-52', 'Recursos huérfanos tratados', 'PASS'),
  audit('OPSAUD-53', 'DNS/TLS/URLs final', 'PASS'),
  audit('OPSAUD-54', 'Integraciones externas tratadas', 'PASS'),
  audit('OPSAUD-55', 'Coste residual documentado', 'PASS'),
  audit('OPSAUD-56', 'Retrospectiva completa', 'PASS'),
  audit('OPSAUD-57', 'Lecciones registradas', 'PASS'),
  audit('OPSAUD-58', 'Riesgos residuales firmados', 'PASS'),
  audit('OPSAUD-59', 'Paquete final completo', 'PASS'),
  audit('OPSAUD-60', 'Certificado y comunicación', 'PASS'),
]);

export const STAGE9_AUTHORIZATIONS = freezeEntries([
  {
    id: 'AUTH-E9-OBSERVE',
    action: 'Lectura de métricas, logs y costes',
    requirement: 'Sí',
    authority: 'Operations/Cloud Owner',
    defaultStatus: 'PENDING',
  },
  {
    id: 'AUTH-E9-SANDBOX',
    action: 'Reconciliación o smoke controlado',
    requirement: 'Sí',
    authority: 'Application Owner',
    defaultStatus: 'PENDING',
  },
  {
    id: 'AUTH-E9-ACCESS',
    action: 'Revocar accesos temporales',
    requirement: 'Sí',
    authority: 'Security Owner',
    defaultStatus: 'PENDING',
  },
  {
    id: 'AUTH-E9-DATA',
    action: 'Eliminar/anonymizar datos',
    requirement: 'Sí',
    authority: 'Security + Closure',
    defaultStatus: 'PENDING',
  },
  {
    id: 'AUTH-E9-DESTROY',
    action: 'Destruir recursos cloud',
    requirement: 'Sí, explícita',
    authority: 'Closure Approver',
    defaultStatus: 'DENIED_BY_DEFAULT',
  },
  {
    id: 'AUTH-E9-ARCHIVE',
    action: 'Archivar repositorio',
    requirement: 'Sí, explícita',
    authority: 'Closure Approver',
    defaultStatus: 'DENIED_BY_DEFAULT',
  },
  {
    id: 'AUTH-E9-RESTORE',
    action: 'Recrear entorno para entrevista',
    requirement: 'Sí',
    authority: 'Closure + Cloud',
    defaultStatus: 'PENDING',
  },
]);

export const STAGE9_ACTION_AUTHORITY = Object.freeze({
  OBSERVE: 'AUTH-E9-OBSERVE',
  SANDBOX_RECONCILIATION: 'AUTH-E9-SANDBOX',
  REVOKE_ACCESS: 'AUTH-E9-ACCESS',
  DATA_TREATMENT: 'AUTH-E9-DATA',
  DESTROY: 'AUTH-E9-DESTROY',
  ARCHIVE_REPOSITORY: 'AUTH-E9-ARCHIVE',
  RESTORE: 'AUTH-E9-RESTORE',
});

export const STAGE9_GATES = freezeEntries([
  {
    id: 'GATE-E9-01',
    name: 'Preparación operativa',
    allowedResults: ['PASS', 'FAIL', 'BLOCKED_AUTH'],
    requirements: [
      'GATE-E8-03 PASS',
      'baseline coincidente',
      'carta completa',
      'modo operativo aprobado',
      'roles y autorizaciones',
      'inventario inicial',
      'dashboard/alarmas activos',
      'presupuesto/control de coste',
      'repo y URLs verificables',
      'registro de PENDING',
      'índice de evidencia iniciado',
      'cero P0/P1 al inicio',
    ],
  },
  {
    id: 'GATE-E9-02',
    name: 'Operación, seguridad y transición',
    allowedResults: ['PASS', 'FAIL', 'BLOCKED_AUTH', 'BLOCKED_EXTERNAL'],
    requirements: [
      'ventana completada o hold formalizado',
      'SLI/SLO internos evaluados',
      'cero P0/P1 abiertos',
      'cero alarmas críticas abiertas',
      'PENDING e invariantes controlados',
      'costes dentro de decisión aprobada',
      'accesos revisados',
      'secretos y logs limpios',
      'retención aprobada',
      'decisión hold/decommission',
      'rehearsal de cleanup aprobado',
      'evidencia suficiente',
    ],
  },
  {
    id: 'GATE-E9-03',
    name: 'Cierre final',
    allowedResults: ['PASS', 'FAIL', 'BLOCKED_AUTH'],
    routes: [
      {
        name: 'Retención controlada',
        requirements: [
          'CLOSED_RETAINED',
          'owner activo',
          'presupuesto',
          'expiry',
          'URLs/repo en estado acordado',
          'acceso mínimo',
          'plan de decommission futuro',
          'riesgos aceptados',
        ],
      },
      {
        name: 'Decommission completo',
        requirements: [
          'CLOSED_DECOMMISSIONED',
          'cleanup autorizado y ejecutado',
          'recursos huérfanos tratados',
          'coste residual documentado',
          'accesos revocados',
          'datos tratados',
          'repo/evidencia preservados',
          'URLs actualizadas',
          'certificado firmado',
        ],
      },
    ],
    requirements: [
      'auditoría final completa',
      'paquete de cierre íntegro',
      'retrospectiva',
      'riesgos aceptados',
      'comunicación final',
    ],
  },
]);

export const STAGE9_REPORT_SECTIONS = Object.freeze([
  'Resumen ejecutivo',
  'Estado de entrada y GATE-E8-03',
  'Carta de operación y cierre',
  'Release, SHAs y baseline',
  'Modo operativo y autorizaciones',
  'Inventario de recursos',
  'Tags, owners y expiración',
  'Ventana de observación',
  'Dashboard, alarmas y checks',
  'Salud de SPA y API',
  'Métricas de negocio',
  'PENDING y reconciliación',
  'Invariantes de inventario/entrega',
  'Logs, privacidad y datos',
  'Incidentes y runbooks',
  'Sandbox y cuenta compartida',
  'Accesos y secretos',
  'Costes, budget y forecast',
  'Hold o decommission',
  'Retención y eliminación',
  'Archivo de evidencia',
  'Repositorio y README',
  'Rehearsal de cleanup',
  'Cleanup o retención ejecutada',
  'Recursos huérfanos y coste residual',
  'DNS, TLS, URLs e integraciones',
  'Retrospectiva y lecciones',
  'Riesgos y desviaciones',
  'Auditoría OPSAUD-01..60',
  'GATE-E9-01',
  'GATE-E9-02',
  'GATE-E9-03',
  'Certificado de cierre',
  'Comunicación final',
]);
